Rewards Injector improvments
defilytica/balancer-ops-frontend pull request #14
Opened 2024-08-30 13:42 UTC by Hyferion

- use addressbook hook in rewards injector
- show missing funds in rewards injector

2024-09-05 09:36 UTC, Xeonus requested changes

2024-09-06 09:45 UTC, Hyferion commented on app/payload-builder/add-reward-to-gauge/page.tsx
> +  console.log(network);
fixed

2024-09-06 09:46 UTC, Hyferion commented on app/rewards-injector/page.tsx
> +  console.log(tokenSymbol)
fixed

2024-09-06 09:47 UTC, Hyferion commented on app/rewards-injector/page.tsx
>    useEffect(() => {
Moved the rewards injector into a component, load the address book a component higher

2024-09-06 10:58 UTC, merged